package com.TheEcommerce.SpringBootTheECommerceProjectKafkaProducer.service;

import com.TheEcommerce.SpringBootTheECommerceProjectKafkaProducer.model.Sale;
import com.TheEcommerce.SpringBootTheECommerceProjectKafkaProducer.model.orderservices.OrderService;
import com.TheEcommerce.SpringBootTheECommerceProjectKafkaProducer.model.paymentbroker.PaymentBroker;

import java.util.List;

public interface KafkaService {

    public void publishCsvData(List<Sale> saleList);

    public void publishOrderServicesFiles(List<String> orderServicesFilesList);

    public void publishAutoGeneratedOrderServices(List<OrderService> orderServiceList);

    public void publishAutoGeneratedPaymentBroker(List<PaymentBroker> paymentBrokerList);

}
